
# yaml-language-server: $schema=https://agentgateway.dev/schema/config
binds:
- port: 6000
  listeners:
  - routes:
    - policies:
        cors:
          allowOrigins:
          - "*"
          allowHeaders:
          - "*"
          exposeHeaders:
          - "Mcp-Session-Id"
      backends:
      - mcp:
          targets:
          - name: jenkins
            mcp:
              host: "http://jenkins-mcp:6500/mcp"
          - name: github
            mcp:
              host: "http://github-mcp:6501/mcp"
          - name: gitlab
            mcp:
              host: "http://gitlab-mcp:6502/mcp"
          - name: snow
            mcp:
              host: "http://snow-mcp:6503/mcp"
          - name: sonar
            mcp:
              host: "http://sonar-mcp:6504/mcp"
